name: Push

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

env:
  NODE_VERSION: '20'

jobs:
  spellcheck:
    uses: ./.github/workflows/spellcheck.yml
    with:
      node-version: ${{ env.NODE_VERSION }}
