name: release-drafter

on:
  workflow_call:

jobs:
  release-drafter:
    name: release-drafter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
