name: release-drafter

on:
  push:
    branches:
      - master
  workflow_call:
    outputs:
      body:
        description: The body of the drafted release.
        value: ${{ jobs.release-drafter.outputs.body }}
      html_url:
        description: The URL users can navigate to in order to view the release
        value: ${{ jobs.release-drafter.outputs.html_url }}
      id:
        description: The ID of the release that was created or updated.
        value: ${{ jobs.release-drafter.outputs.id }}
      major_version:
        description: The next major version number. For example, if the last tag or release was v1.2.3, the value would be v2.0.0.
        value: ${{ jobs.release-drafter.outputs.major_version }}
      minor_version:
        description: The next minor version number. For example, if the last tag or release was v1.2.3, the value would be v1.3.0.
        value: ${{ jobs.release-drafter.outputs.minor_version }}
      name:
        description: The name of the release.
        value: ${{ jobs.release-drafter.outputs.name }}
      patch_version:
        description: The next patch version number. For example, if the last tag or release was v1.2.3, the value would be v1.2.4.
        value: ${{ jobs.release-drafter.outputs.patch_version }}
      resolved_version:
        description: The next resolved version number, based on GitHub labels.
        value: ${{ jobs.release-drafter.outputs.resolved_version }}
      tag_name:
        description: The name of the tag associated with the release.
        value: ${{ jobs.release-drafter.outputs.tag_name }}
      upload_url:
        description: The URL for uploading assets to the release, which could be used by GitHub Actions for additional uses, for example the @actions/upload-release-asset GitHub Action.
        value: ${{ jobs.release-drafter.outputs.upload_url }}

jobs:
  release-drafter:
    name: release-drafter
    outputs:
      body: ${{ steps.release.outputs.body }}
      html_url: ${{ steps.release.outputs.html_url }}
      id: ${{ steps.release.outputs.id }}
      major_version: ${{ steps.release.outputs.major_version }}
      minor_version: ${{ steps.release.outputs.minor_version }}
      name: ${{ steps.release.outputs.name }}
      patch_version: ${{ steps.release.outputs.patch_version }}
      resolved_version: ${{ steps.release.outputs.resolved_version }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.ref }}
